---
kind: pipeline
type: docker
name: build
steps:
- name: build
  image: archlinux
  environment:
    USER: builder
    INPUT_EXTRA_NIX_CONFIG: |
      experimental-features = nix-command flakes
      system-features = nixos-test benchmark big-parallel kvm recursive-nix
      substituters = https://imlonghao.cachix.org https://nrdxp.cachix.org https://nix-community.cachix.org https://cache.nixos.org
      trusted-public-keys = imlonghao.cachix.org-1:KGQ7+R1BXo2NsoeAxKLPfGAiHz5ofCmZO4hih7u/2Q8= nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    INPUT_INSTALL_URL: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
    GITHUB_ENV: /dev/null
    GITHUB_PATH: /dev/null
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/nix/var/nix/profiles/default/bin
    CACHIX_AUTH_TOKEN:
      from_secret: CACHIX_AUTH_TOKEN
  commands:
  - useradd -md /home/$USER $USER
  - patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && bsdtar -C / -xvf "$patched_glibc"
  - pacman -Sy --noconfirm sudo
  - INPUT_INSTALL_OPTIONS= sh <(curl -L https://raw.githubusercontent.com/cachix/install-nix-action/76f99676004c1530baa4c77a5336baa12ec4dc99/lib/install-nix.sh)
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
