keys:
  - &me_canokey 86962971BE75940CBB19297D29B038B368839CB5
  - &vps_mailcow age14h9xqddgcue0mxajxydwj0yq5vc9r452sds2dptnturvwf4reqtsnnk3md
  - &vps_buyvmuslasvegas1 age1tn2crgjwffdhvn8k7h2yd7et7ze3pqcuzqm80v2pq9pglcdkwyys5fuqyk
  - &vps_buyvmusmiami1 age17udapsqm2lx6u6jkcugwlu2a90sv6uasfzap0vd2du5ecxrsn44q6e82pu
  - &vps_hosthatchsgsingapore1 age1m7e9lwfnu8x2eele4rmflhn8s8vhcf85s4lpt5x4jgd9kyu25s3s3jn3cg
  - &vps_misakauklondon1 age1qsrtlhdmp8sfgkwux0r6frtv9z5apc38ggtgwv6n47pznf43k3zsv0ms8w
  - &vps_starrydnscnhongkong1 age1w52xml8esykwg2hgvqn625q9fa0zfz3ynvcn5tugmsqau6jpcv0sezqzut
  - &vps_uovzcnhongkong1 age1wm8t6ajej5e7n6svsfsq0gtv69y369gauvhhqspezt77m2h2ceysr9y6pk
  - &vps_hertzdefalkenstein1 age1qdn82sandycx45gprty2504q62qxmhtfc8ztrmfq7lpsy9lkspzs4xuwkx
  - &vps_virmachustampa1 age1u3uszgtvyfy4gmsq4tk7hu06ag63rjzza9gvd9fky8kew03safnqwkkp48
  - &vps_hosthatchsestockholm1 age1x7lktd64mjxar0hahhmz4pkp3gk74vcm46tfmyvet5e2x93usyksufjrtc
  - &vps_oracledefrankfurt1 age1a8n7e54k57fsczpu0zxqadmyp3aal9prc9ez3l729r6d6aqjnvaqzng7ar
  - &vps_terrahostnosandefjord1 age1zhq4z3srfk0m7njlcgem2av3mzylk89tcfq0t7fhxd0q6xq97ueqtj4dg4
  - &vps_vpsdeduesseldorf1 age1yutf6j4sr5lwxnrmh8crp585r6q7dkhxyyt04gxaqyp7kf5565nsdksxdk
  - &vps_vpsausydney1 age10hs4v4utyhykkgwdyagqng54apnf4qsjunjnlarwcg4l0ydm4f3qhz49sj
  - &vps_idcwikicnhongkong1 age1va69x2r5gl790g8d9zd9q3qj5ynvalakvgz55ygrzhrrnc8kl3ys4fla94
  - &vps_misakadeberlin1 age1dyk0dt4kzj59yxhj2dxwkxwecy6c9xh9k5p8722r94sg45fcvu8qmkf5m6
  - &vps_vpsussanjose1 age1mvq9x84yde6a9gaer77t84dekpe23wsnxrrjw286kj0gsu6y6ens70kzuk
  - &vps_ovhfrgravelines1 age173tunxse0c6s9ppmdnszsd6quxmm7zft7tvx8p6c5qvq3rqhgagqh5m5pt
  - &vps_buyvmluroost1 age13pa3dsvdsygpxxlc2hannvxx4qh03280me3s7xdrmenuvf7mmcvsdckylx
  - &vps_vpsdefrankfurt1 age1x8zq7qr5prjktk6j6emu98vzl2rgcjq804kuwp34cfj6jgh2pf5q46gma2
  - &vps_wirecatussantaclara1 age1xccl6xa43q4v4gacen5942djrpd3ms7422ent0362u7dtpdd0c6sq7ccwf
  - &vps_twdscntaibei1 age17u6hxy0wv98kt03sezgtangyfv63ynk303x4t4shqsanzc2vxgxszdxfsh
  - &vps_vultrusseattle1 age1hj7jtsghtle6gn72azh7j23u670wgu6y29aeh5scpfxvdn5h5ajs9924cs
  - &vps_virtuafrlille1 age194npt4zgv99kszaaf96kv5rx79uxzrjq8m9j8fv25je08exa75usuatap3
  - &vps_f4uskansas1 age1hsukvd00p3k8mt9cmlau5fc4tjfrwhwhxx8la3h9lad5k5ga0e2qc8t7y8
  - &vps_dmituslosangeles1 age1mxrjyaswxznnvfa8m6hv0eewge6nvedst5nl9wml4ehww9kgjvqsqugpsz
creation_rules:
  - path_regex: secrets/shadow.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_mailcow
      - *vps_buyvmuslasvegas1
      - *vps_buyvmusmiami1
      - *vps_hosthatchsgsingapore1
      - *vps_misakauklondon1
      - *vps_starrydnscnhongkong1
      - *vps_uovzcnhongkong1
      - *vps_virmachustampa1
      - *vps_hosthatchsestockholm1
      - *vps_oracledefrankfurt1
      - *vps_vpsdeduesseldorf1
      - *vps_vpsausydney1
      - *vps_idcwikicnhongkong1
      - *vps_misakadeberlin1
      - *vps_ovhfrgravelines1
      - *vps_buyvmluroost1
      - *vps_vpsdefrankfurt1
      - *vps_wirecatussantaclara1
      - *vps_twdscntaibei1
      - *vps_vultrusseattle1
      - *vps_virtuafrlille1
      - *vps_f4uskansas1
      - *vps_dmituslosangeles1
  - path_regex: secrets/k3s.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsgsingapore1
      - *vps_starrydnscnhongkong1
      - *vps_uovzcnhongkong1
      - *vps_virmachustampa1
  - path_regex: secrets/vector.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmusmiami1
  - path_regex: hosts/mailcow/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_mailcow
  - path_regex: hosts/buyvmuslasvegas1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmuslasvegas1
  - path_regex: hosts/buyvmusmiami1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmusmiami1
  - path_regex: hosts/hosthatchsgsingapore1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsgsingapore1
  - path_regex: hosts/misakauklondon1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_misakauklondon1
  - path_regex: hosts/starrydnscnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_starrydnscnhongkong1
  - path_regex: hosts/uovzcnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_uovzcnhongkong1
  - path_regex: hosts/hertzdefalkenstein1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hertzdefalkenstein1
  - path_regex: hosts/virmachustampa1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_virmachustampa1
  - path_regex: hosts/hosthatchsestockholm1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsestockholm1
  - path_regex: hosts/oracledefrankfurt1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_oracledefrankfurt1
  - path_regex: hosts/terrahostnosandefjord1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_terrahostnosandefjord1
  - path_regex: hosts/vpsdeduesseldorf1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsdeduesseldorf1
  - path_regex: hosts/vpsausydney1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsausydney1
  - path_regex: hosts/idcwikicnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_idcwikicnhongkong1
  - path_regex: hosts/misakadeberlin1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_misakadeberlin1
  - path_regex: hosts/vpsussanjose1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsussanjose1
  - path_regex: hosts/ovhfrgravelines1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_ovhfrgravelines1
  - path_regex: hosts/buyvmluroost1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmluroost1
  - path_regex: hosts/vpsdefrankfurt1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsdefrankfurt1
  - path_regex: hosts/wirecatussantaclara1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_wirecatussantaclara1
  - path_regex: hosts/twdscntaibei1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_twdscntaibei1
  - path_regex: hosts/vultrusseattle1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vultrusseattle1
  - path_regex: hosts/virtuafrlille1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_virtuafrlille1
  - path_regex: hosts/f4uskansas1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_f4uskansas1
  - path_regex: hosts/dmituslosangeles1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_dmituslosangeles1
