keys:
  - &me_yubikey 57957BAD5D038B07C28EF49A15B26377262268C1
  - &vps_mailcow age14h9xqddgcue0mxajxydwj0yq5vc9r452sds2dptnturvwf4reqtsnnk3md
  - &vps_hetznerdefalkenstein1 age17mfxq9tatls5n326dh0dragrz2lxsx0ka2pvc55wjhztm38adypsfl99hy
creation_rules:
  - path_regex: secrets/shadow.yml$
    pgp: 57957BAD5D038B07C28EF49A15B26377262268C1
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_mailcow
      - *vps_hetznerdefalkenstein1
  - path_regex: secrets/k3s.yml$
    pgp: 57957BAD5D038B07C28EF49A15B26377262268C1
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_hetznerdefalkenstein1
  - path_regex: hosts/mailcow/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_mailcow
  - path_regex: hosts/hetznerdefalkenstein1/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_hetznerdefalkenstein1
