keys:
  - &me_canokey 86962971BE75940CBB19297D29B038B368839CB5
  - &vps_mailcow age14h9xqddgcue0mxajxydwj0yq5vc9r452sds2dptnturvwf4reqtsnnk3md
  - &vps_buyvmuslasvegas1 age1tn2crgjwffdhvn8k7h2yd7et7ze3pqcuzqm80v2pq9pglcdkwyys5fuqyk
  - &vps_buyvmusmiami1 age17udapsqm2lx6u6jkcugwlu2a90sv6uasfzap0vd2du5ecxrsn44q6e82pu
  - &vps_hosthatchsgsingapore1 age1m7e9lwfnu8x2eele4rmflhn8s8vhcf85s4lpt5x4jgd9kyu25s3s3jn3cg
  - &vps_misakauklondon1 age1qsrtlhdmp8sfgkwux0r6frtv9z5apc38ggtgwv6n47pznf43k3zsv0ms8w
  - &vps_nexusbytesuslosangeles1 age169f9w428zvwckcrldzvtgd96twugevm54fw8zxl2929ysxp3nadsujkgek
  - &vps_starrydnscnhongkong1 age1w52xml8esykwg2hgvqn625q9fa0zfz3ynvcn5tugmsqau6jpcv0sezqzut
  - &vps_uovzcnhongkong1 age1wm8t6ajej5e7n6svsfsq0gtv69y369gauvhhqspezt77m2h2ceysr9y6pk
  - &vps_hertzdefalkenstein1 age1qdn82sandycx45gprty2504q62qxmhtfc8ztrmfq7lpsy9lkspzs4xuwkx
  - &vps_virmachusbuffalo1 age1u3uszgtvyfy4gmsq4tk7hu06ag63rjzza9gvd9fky8kew03safnqwkkp48
  - &vps_hetznerdefalkenstein2 age18g6r3csxxua0r59a5szzmzurr9l7l4tg3qkuxfrfqjrv9v3j359s2gsl8d
  - &vps_hosthatchsestockholm1 age1x7lktd64mjxar0hahhmz4pkp3gk74vcm46tfmyvet5e2x93usyksufjrtc
  - &vps_oracledefrankfurt1 age1a8n7e54k57fsczpu0zxqadmyp3aal9prc9ez3l729r6d6aqjnvaqzng7ar
  - &vps_terrahostnosandefjord1 age1zhq4z3srfk0m7njlcgem2av3mzylk89tcfq0t7fhxd0q6xq97ueqtj4dg4
  - &vps_vpsdeduesseldorf1 age1yutf6j4sr5lwxnrmh8crp585r6q7dkhxyyt04gxaqyp7kf5565nsdksxdk
  - &vps_vpsausydney1 age10hs4v4utyhykkgwdyagqng54apnf4qsjunjnlarwcg4l0ydm4f3qhz49sj
  - &vps_idcwikicnhongkong1 age1va69x2r5gl790g8d9zd9q3qj5ynvalakvgz55ygrzhrrnc8kl3ys4fla94
creation_rules:
  - path_regex: secrets/shadow.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_mailcow
      - *vps_buyvmuslasvegas1
      - *vps_buyvmusmiami1
      - *vps_hosthatchsgsingapore1
      - *vps_misakauklondon1
      - *vps_nexusbytesuslosangeles1
      - *vps_starrydnscnhongkong1
      - *vps_uovzcnhongkong1
      - *vps_virmachusbuffalo1
      - *vps_hetznerdefalkenstein2
      - *vps_hosthatchsestockholm1
      - *vps_oracledefrankfurt1
      - *vps_vpsdeduesseldorf1
      - *vps_vpsausydney1
      - *vps_idcwikicnhongkong1
  - path_regex: secrets/k3s.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsgsingapore1
      - *vps_nexusbytesuslosangeles1
      - *vps_starrydnscnhongkong1
      - *vps_uovzcnhongkong1
      - *vps_virmachusbuffalo1
      - *vps_hetznerdefalkenstein2
  - path_regex: hosts/mailcow/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_mailcow
  - path_regex: hosts/buyvmuslasvegas1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmuslasvegas1
  - path_regex: hosts/buyvmusmiami1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_buyvmusmiami1
  - path_regex: hosts/hosthatchsgsingapore1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsgsingapore1
  - path_regex: hosts/misakauklondon1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_misakauklondon1
  - path_regex: hosts/nexusbytesuslosangeles1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_nexusbytesuslosangeles1
  - path_regex: hosts/starrydnscnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_starrydnscnhongkong1
  - path_regex: hosts/uovzcnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_uovzcnhongkong1
  - path_regex: hosts/hertzdefalkenstein1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hertzdefalkenstein1
  - path_regex: hosts/virmachusbuffalo1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_virmachusbuffalo1
  - path_regex: hosts/hetznerdefalkenstein2/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hetznerdefalkenstein2
  - path_regex: hosts/hosthatchsestockholm1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_hosthatchsestockholm1
  - path_regex: hosts/oracledefrankfurt1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_oracledefrankfurt1
  - path_regex: hosts/terrahostnosandefjord1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_terrahostnosandefjord1
  - path_regex: hosts/vpsdeduesseldorf1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsdeduesseldorf1
  - path_regex: hosts/vpsausydney1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_vpsausydney1
  - path_regex: hosts/idcwikicnhongkong1/secrets.yml$
    key_groups:
    - pgp:
      - *me_canokey
      age:
      - *vps_idcwikicnhongkong1
