keys:
  - &me_canokey 86962971BE75940CBB19297D29B038B368839CB5
  - &vps_breezehostusdallas1 age1shcwxwjp6sysq2frdxq4zjzwwza9hzjlpv82yy8jl3g0dq9hv43qfd0lx2
  - &vps_buyvmluroost1 age13pa3dsvdsygpxxlc2hannvxx4qh03280me3s7xdrmenuvf7mmcvsdckylx
  - &vps_buyvmuslasvegas1 age1tn2crgjwffdhvn8k7h2yd7et7ze3pqcuzqm80v2pq9pglcdkwyys5fuqyk
  - &vps_buyvmusmiami1 age17udapsqm2lx6u6jkcugwlu2a90sv6uasfzap0vd2du5ecxrsn44q6e82pu
  - &vps_clawcloudcnhongkong1 age1gg4ex52vwueqf93f53334uzr4mh5lzqt36xh6th3ydz7f28m3yhsgc4g2a
  - &vps_coalcloudcnhongkong1 age139x2kfpn60v9lcmn94p396jyg6yn0az4h4hequgrxptwtjjqla0qdp22el
  - &vps_dmitcnhongkong1 age1kplhd4zrmjgegmx6epzjpq0xug6uz9wuvjgdx5ns6thtkmz0nyrqcd43nx
  - &vps_dmituslosangeles1 age1mxrjyaswxznnvfa8m6hv0eewge6nvedst5nl9wml4ehww9kgjvqsqugpsz
  - &vps_f4uskansas1 age1hsukvd00p3k8mt9cmlau5fc4tjfrwhwhxx8la3h9lad5k5ga0e2qc8t7y8
  - &vps_hosthatchsestockholm1 age1x7lktd64mjxar0hahhmz4pkp3gk74vcm46tfmyvet5e2x93usyksufjrtc
  - &vps_hosthatchsgsingapore1 age1m7e9lwfnu8x2eele4rmflhn8s8vhcf85s4lpt5x4jgd9kyu25s3s3jn3cg
  - &vps_misakadeberlin1 age1dyk0dt4kzj59yxhj2dxwkxwecy6c9xh9k5p8722r94sg45fcvu8qmkf5m6
  - &vps_misakauklondon1 age1qsrtlhdmp8sfgkwux0r6frtv9z5apc38ggtgwv6n47pznf43k3zsv0ms8w
  - &vps_oracledefrankfurt1 age1a8n7e54k57fsczpu0zxqadmyp3aal9prc9ez3l729r6d6aqjnvaqzng7ar
  - &vps_ovhcabeauharnois1 age15a0gm84zgxt0ah5a5csympuv7htrtpymrh0m8lm7y6w39p483p8sqrdu4x
  - &vps_ovhcabeauharnois2 age16fcxnydpjxw3l2ndngxtf8mqt5f3nj4cywh9atsuzstv49fxwcns450pcl
  - &vps_ovhfrgravelines1 age173tunxse0c6s9ppmdnszsd6quxmm7zft7tvx8p6c5qvq3rqhgagqh5m5pt
  - &vps_serverfactorynleygelshoven1 age1ds6c4dvtksgzmrsv7xpgn397xjjvs03zhta3vc9ta3uhygauz9dsdq0az6
  - &vps_starrydnscnhongkong1 age1w52xml8esykwg2hgvqn625q9fa0zfz3ynvcn5tugmsqau6jpcv0sezqzut
  - &vps_terrahostnosandefjord1 age1zhq4z3srfk0m7njlcgem2av3mzylk89tcfq0t7fhxd0q6xq97ueqtj4dg4
  - &vps_twdscntaibei1 age17u6hxy0wv98kt03sezgtangyfv63ynk303x4t4shqsanzc2vxgxszdxfsh
  - &vps_virtuafrlille1 age194npt4zgv99kszaaf96kv5rx79uxzrjq8m9j8fv25je08exa75usuatap3
  - &vps_vpsausydney1 age10hs4v4utyhykkgwdyagqng54apnf4qsjunjnlarwcg4l0ydm4f3qhz49sj
  - &vps_vpsdefrankfurt1 age1x8zq7qr5prjktk6j6emu98vzl2rgcjq804kuwp34cfj6jgh2pf5q46gma2
  - &vps_vpsjptokyo1 age1un5x9uu4lf2zkfps27x0zph6htpnejlrdsgyzheq9w7ukmkaxvhqwdzl4s
  - &vps_vpsussanjose1 age1mvq9x84yde6a9gaer77t84dekpe23wsnxrrjw286kj0gsu6y6ens70kzuk
  - &vps_wirecatussantaclara1 age1xccl6xa43q4v4gacen5942djrpd3ms7422ent0362u7dtpdd0c6sq7ccwf
  - &vps_xentainusdallas1 age15tfsen4ekuh9s4l3v0rjstnc7uaeplmwuqehnd0grh5sz70h944sr32xal
creation_rules:
  - path_regex: secrets/shadow.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmuslasvegas1
          - *vps_buyvmusmiami1
          - *vps_hosthatchsgsingapore1
          - *vps_misakauklondon1
          - *vps_starrydnscnhongkong1
          - *vps_hosthatchsestockholm1
          - *vps_oracledefrankfurt1
          - *vps_vpsausydney1
          - *vps_misakadeberlin1
          - *vps_ovhfrgravelines1
          - *vps_buyvmluroost1
          - *vps_vpsdefrankfurt1
          - *vps_wirecatussantaclara1
          - *vps_twdscntaibei1
          - *vps_virtuafrlille1
          - *vps_f4uskansas1
          - *vps_dmitcnhongkong1
          - *vps_dmituslosangeles1
          - *vps_serverfactorynleygelshoven1
          - *vps_xentainusdallas1
          - *vps_breezehostusdallas1
          - *vps_vpsjptokyo1
          - *vps_coalcloudcnhongkong1
          - *vps_clawcloudcnhongkong1
          - *vps_ovhcabeauharnois1
          - *vps_terrahostnosandefjord1
          - *vps_ovhcabeauharnois2
          - *vps_vpsussanjose1
  - path_regex: secrets/vector.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmusmiami1
  - path_regex: secrets/sing-box.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_twdscntaibei1
          - *vps_dmituslosangeles1
          - *vps_starrydnscnhongkong1
          - *vps_vpsausydney1
          - *vps_misakadeberlin1
          - *vps_hosthatchsgsingapore1
          - *vps_vpsjptokyo1
          - *vps_coalcloudcnhongkong1
  - path_regex: secrets/openobserve.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_dmituslosangeles1
          - *vps_vpsausydney1
          - *vps_serverfactorynleygelshoven1
          - *vps_clawcloudcnhongkong1
          - *vps_oracledefrankfurt1
          - *vps_hosthatchsgsingapore1
          - *vps_buyvmuslasvegas1
          - *vps_buyvmusmiami1
  - path_regex: secrets/k3s-server.txt$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_misakauklondon1
          - *vps_misakadeberlin1
          - *vps_serverfactorynleygelshoven1
  - path_regex: secrets/k3s-agent.txt$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_misakauklondon1
          - *vps_misakadeberlin1
          - *vps_serverfactorynleygelshoven1
          - *vps_ovhcabeauharnois1
          - *vps_wirecatussantaclara1
          - *vps_hosthatchsestockholm1
          - *vps_hosthatchsgsingapore1
          - *vps_ovhfrgravelines1
          - *vps_vpsausydney1
          - *vps_clawcloudcnhongkong1
          - *vps_oracledefrankfurt1
          - *vps_ovhcabeauharnois2
  - path_regex: secrets/ranet.txt$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmuslasvegas1
          - *vps_buyvmusmiami1
          - *vps_hosthatchsgsingapore1
          - *vps_misakauklondon1
          - *vps_starrydnscnhongkong1
          - *vps_hosthatchsestockholm1
          - *vps_oracledefrankfurt1
          - *vps_vpsausydney1
          - *vps_misakadeberlin1
          - *vps_ovhfrgravelines1
          - *vps_buyvmluroost1
          - *vps_vpsdefrankfurt1
          - *vps_wirecatussantaclara1
          - *vps_twdscntaibei1
          - *vps_virtuafrlille1
          - *vps_f4uskansas1
          - *vps_dmituslosangeles1
          - *vps_serverfactorynleygelshoven1
          - *vps_xentainusdallas1
          - *vps_breezehostusdallas1
          - *vps_vpsjptokyo1
          - *vps_coalcloudcnhongkong1
          - *vps_clawcloudcnhongkong1
          - *vps_ovhcabeauharnois1
          - *vps_vpsussanjose1
          - *vps_terrahostnosandefjord1
          - *vps_ovhcabeauharnois2
  - path_regex: hosts/buyvmuslasvegas1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmuslasvegas1
  - path_regex: hosts/buyvmusmiami1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmusmiami1
  - path_regex: hosts/hosthatchsgsingapore1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_hosthatchsgsingapore1
  - path_regex: hosts/misakauklondon1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_misakauklondon1
  - path_regex: hosts/starrydnscnhongkong1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_starrydnscnhongkong1
  - path_regex: hosts/hosthatchsestockholm1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_hosthatchsestockholm1
  - path_regex: hosts/oracledefrankfurt1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_oracledefrankfurt1
  - path_regex: hosts/terrahostnosandefjord1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_terrahostnosandefjord1
  - path_regex: hosts/vpsausydney1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_vpsausydney1
  - path_regex: hosts/misakadeberlin1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_misakadeberlin1
  - path_regex: hosts/vpsussanjose1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_vpsussanjose1
  - path_regex: hosts/ovhfrgravelines1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_ovhfrgravelines1
  - path_regex: hosts/buyvmluroost1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_buyvmluroost1
  - path_regex: hosts/vpsdefrankfurt1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_vpsdefrankfurt1
  - path_regex: hosts/wirecatussantaclara1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_wirecatussantaclara1
  - path_regex: hosts/twdscntaibei1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_twdscntaibei1
  - path_regex: hosts/virtuafrlille1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_virtuafrlille1
  - path_regex: hosts/f4uskansas1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_f4uskansas1
  - path_regex: hosts/dmituslosangeles1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_dmituslosangeles1
  - path_regex: hosts/dmitcnhongkong1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_dmitcnhongkong1
  - path_regex: hosts/serverfactorynleygelshoven1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_serverfactorynleygelshoven1
  - path_regex: hosts/xentainusdallas1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_xentainusdallas1
  - path_regex: hosts/breezehostusdallas1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_breezehostusdallas1
  - path_regex: hosts/vpsjptokyo1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_vpsjptokyo1
  - path_regex: hosts/coalcloudcnhongkong1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_coalcloudcnhongkong1
  - path_regex: hosts/clawcloudcnhongkong1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_clawcloudcnhongkong1
  - path_regex: hosts/ovhcabeauharnois1/secrets.yml$
    key_groups:
      - pgp:
          - *me_canokey
        age:
          - *vps_ovhcabeauharnois1
