keys:
  - &me_yubikey 57957BAD5D038B07C28EF49A15B26377262268C1
  - &vps_mailcow age14h9xqddgcue0mxajxydwj0yq5vc9r452sds2dptnturvwf4reqtsnnk3md
  - &vps_hetznerdefalkenstein1 age17mfxq9tatls5n326dh0dragrz2lxsx0ka2pvc55wjhztm38adypsfl99hy
  - &vps_buyvmuslasvegas1 age1tn2crgjwffdhvn8k7h2yd7et7ze3pqcuzqm80v2pq9pglcdkwyys5fuqyk
  - &vps_buyvmusmiami1 age17udapsqm2lx6u6jkcugwlu2a90sv6uasfzap0vd2du5ecxrsn44q6e82pu
  - &vps_hosthatchsgsingapore1 age1m7e9lwfnu8x2eele4rmflhn8s8vhcf85s4lpt5x4jgd9kyu25s3s3jn3cg
creation_rules:
  - path_regex: secrets/shadow.yml$
    pgp: 57957BAD5D038B07C28EF49A15B26377262268C1
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_mailcow
      - *vps_hetznerdefalkenstein1
  - path_regex: secrets/k3s.yml$
    pgp: 57957BAD5D038B07C28EF49A15B26377262268C1
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_hetznerdefalkenstein1
      - *vps_hosthatchsgsingapore1
  - path_regex: hosts/mailcow/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_mailcow
  - path_regex: hosts/hetznerdefalkenstein1/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_hetznerdefalkenstein1
  - path_regex: hosts/buyvmuslasvegas1/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_buyvmuslasvegas1
  - path_regex: hosts/buyvmusmiami1/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_buyvmusmiami1
  - path_regex: hosts/hosthatchsgsingapore1/secrets.yml$
    key_groups:
    - pgp:
      - *me_yubikey
      age:
      - *vps_hosthatchsgsingapore1
