systems = ["x86_64-linux"]
include = ["nixosConfigurations.*"]
exclude = []
substituters = [
  "https://imlonghao.cachix.org",
  "https://nix-community.cachix.org",
  "https://cache.numtide.com",
  "https://cache.ysun.co",
  "https://cache.esd.cc"
]
