# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[rait]
src.git = "https://gitlab.com/NickCao/RAIT"
fetch.git = "https://gitlab.com/NickCao/RAIT"
passthru = { vendorSha256 = "sha256-EHkwSSuKrtS0px/a1TUBt13gBNGY8tlpm4sbsoZ1UsY=" }

[babeld]
src.branch = "4via6"
src.git = "https://github.com/imlonghao/babeld"
fetch.github = "imlonghao/babeld"
git.fetchSubmodules = true

[etherguard]
src.git = "https://github.com/KusakabeSi/EtherGuard-VPN"
fetch.github = "KusakabeSi/EtherGuard-VPN"

[q-dns]
src.github = "natesales/q"
fetch.github = "natesales/q"

[deluge_exporter]
src.git = "https://github.com/tobbez/deluge_exporter"
fetch.github = "tobbez/deluge_exporter"

[wesher]
src.git = "https://github.com/costela/wesher"
fetch.github = "costela/wesher"
passthru = { vendorSha256 = "sha256-QoIwp475/+QDYY65TG4DaFH5wbM5eQGREuIJCbBLFy0="}

[mybird]
src.git = "https://github.com/tohojo/bird"
src.branch = "babel-rtt-01"
fetch.github = "tohojo/bird"
