name: Build for cachix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v22
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: imlonghao
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build cache
        run: |
          nix -Lv develop -c nix -Lv build ".#bird-lg-go"
          nix -Lv develop -c nix -Lv build ".#chrony_exporter"
          nix -Lv develop -c nix -Lv build ".#coredns-nat64-rdns"
          nix -Lv develop -c nix -Lv build ".#etherguard"
          nix -Lv develop -c nix -Lv build ".#juicity"
          nix -Lv develop -c nix -Lv build ".#mtrsb"
          nix -Lv develop -c nix -Lv build ".#pingfinder"
          nix -Lv develop -c nix -Lv build ".#rait"
