name: Build for cachix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Nix
        uses: https://github.com/cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f # v31
      - name: Setup Cachix
        uses: https://github.com/cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: imlonghao
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build cache
        run: |
          sed -i "/access-tokens/d" /etc/nix/nix.conf
          nix -Lv develop -c nix -Lv build ".#bird-babel-rtt" \
            ".#bird-lg-go" \
            ".#chrony_exporter" \
            ".#coredns-nat64-rdns" \
            ".#deluge_exporter" \
            ".#dn42debug" \
            ".#etherguard" \
            ".#hachimi" \
            ".#juicity" \
            ".#mtrsb" \
            ".#pingfinder" \
            ".#ranetdebug" \
            ".#strongswan_6" \
            ".#supervxlan" \
            ".#wtt"
