name: Build for cachix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup Nix
        uses: https://github.com/cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31.6.0
        with:
          install_options: --daemon
      - name: Setup Cachix
        uses: https://github.com/cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: imlonghao
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build cache
        run: |
          NIXPKGS_ALLOW_UNFREE=1 nix build --accept-flake-config --impure --extra-experimental-features flakes -vL $(ls pkgs/ | sed 's/^/.#/g' | tr '\n' ' ')
