# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  babeld = {
    pname = "babeld";
    version = "44b3135897726d7155e54ac079ce2a7f911b0c44";
    src = fetchFromGitHub ({
      owner = "imlonghao";
      repo = "babeld";
      rev = "44b3135897726d7155e54ac079ce2a7f911b0c44";
      fetchSubmodules = true;
      sha256 = "sha256-Kx7FIOh68+gJM3CoX6bwEEKh1lkTpS7WUIfRGAkfkIc=";
    });
    date = "2021-06-08";
  };
  deluge_exporter = {
    pname = "deluge_exporter";
    version = "c8a31ede70133498b49b6ac4a1a63b57292e7b47";
    src = fetchFromGitHub ({
      owner = "tobbez";
      repo = "deluge_exporter";
      rev = "c8a31ede70133498b49b6ac4a1a63b57292e7b47";
      fetchSubmodules = false;
      sha256 = "sha256-Yz85DhN3g4YPP+aBX49jLCLDJfgUSAQJgowh0smVVgQ=";
    });
    date = "2023-01-24";
  };
  etherguard = {
    pname = "etherguard";
    version = "7775441e24d68b191fd285d851e58713bead8bc5";
    src = fetchFromGitHub ({
      owner = "KusakabeSi";
      repo = "EtherGuard-VPN";
      rev = "7775441e24d68b191fd285d851e58713bead8bc5";
      fetchSubmodules = false;
      sha256 = "sha256-KOJAD0IUE7HIrCbCg4RuERiyaasz7o053sEL+ZurdVQ=";
    });
    date = "2023-02-23";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  mtrsb = {
    pname = "mtrsb";
    version = "bf67adce5769bbe383ca1ee4014674b84c3c1f6a";
    src = fetchgit {
      url = "https://git.esd.cc/imlonghao/mtr.sb";
      rev = "bf67adce5769bbe383ca1ee4014674b84c3c1f6a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UW+H2HhIeozwAVP8t49AuZxe+RVvPiivvi6bHyMivjQ=";
    };
    vendorSha256 = "sha256-P42z8oJCX6iku9xMUlckEdD5yqu5B1KprAhqm0jvgfg=";
    date = "2023-05-07";
  };
  mybird = {
    pname = "mybird";
    version = "901f906ac470b318d6598c8b25156b0919f70b2a";
    src = fetchFromGitHub ({
      owner = "tohojo";
      repo = "bird";
      rev = "901f906ac470b318d6598c8b25156b0919f70b2a";
      fetchSubmodules = false;
      sha256 = "sha256-PhRmXPTD2cidDwWkKkpVrdGWNr5kEuCZz1B74VXX0BQ=";
    });
    date = "2023-02-26";
  };
  q-dns = {
    pname = "q-dns";
    version = "v0.9.0";
    src = fetchFromGitHub ({
      owner = "natesales";
      repo = "q";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-WPVHMAau3+0jcIrRhRL5dy6h+J13LKj5GwQMJi7hGvo=";
    });
  };
  rait = {
    pname = "rait";
    version = "3191186a959888d4ab34e6440367b9c60508341b";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "3191186a959888d4ab34e6440367b9c60508341b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-MgTskJ5Tp+3PvkZYsCmodRRJWidpzxszrgOo9PoaKhk=";
    };
    vendorSha256 = "sha256-EHkwSSuKrtS0px/a1TUBt13gBNGY8tlpm4sbsoZ1UsY=";
    date = "2023-03-05";
  };
  wesher = {
    pname = "wesher";
    version = "de3e549dd67ad60744cee6bd9a799323ef127567";
    src = fetchFromGitHub ({
      owner = "costela";
      repo = "wesher";
      rev = "de3e549dd67ad60744cee6bd9a799323ef127567";
      fetchSubmodules = false;
      sha256 = "sha256-jt5p6JX7ziRkfL6k0Omgarti8Oaj95LSOxIQkXIO66E=";
    });
    vendorSha256 = "sha256-QoIwp475/+QDYY65TG4DaFH5wbM5eQGREuIJCbBLFy0=";
    date = "2023-02-27";
  };
  wtt = {
    pname = "wtt";
    version = "30a23dd940cc4351d2f09dd6bbb5f1a51675d2bb";
    src = fetchgit {
      url = "https://git.esd.cc/imlonghao/WatchTheTraffic";
      rev = "30a23dd940cc4351d2f09dd6bbb5f1a51675d2bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-2gbZ1eX6MV1PlrkifQObz030Qubxw9F6rS+CnjKTpok=";
    };
    vendorSha256 = "sha256-9ZR+qTCz5b+7wEQDlmniQmfiHhcdt36tmLv/7VYzcLA=";
    date = "2023-03-19";
  };
}
