# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  babeld = {
    pname = "babeld";
    version = "44b3135897726d7155e54ac079ce2a7f911b0c44";
    src = fetchFromGitHub ({
      owner = "imlonghao";
      repo = "babeld";
      rev = "44b3135897726d7155e54ac079ce2a7f911b0c44";
      fetchSubmodules = true;
      sha256 = "sha256-Kx7FIOh68+gJM3CoX6bwEEKh1lkTpS7WUIfRGAkfkIc=";
    });
    date = "2021-06-08";
  };
  deluge_exporter = {
    pname = "deluge_exporter";
    version = "c8a31ede70133498b49b6ac4a1a63b57292e7b47";
    src = fetchFromGitHub ({
      owner = "tobbez";
      repo = "deluge_exporter";
      rev = "c8a31ede70133498b49b6ac4a1a63b57292e7b47";
      fetchSubmodules = false;
      sha256 = "sha256-Yz85DhN3g4YPP+aBX49jLCLDJfgUSAQJgowh0smVVgQ=";
    });
    date = "2023-01-24";
  };
  etherguard = {
    pname = "etherguard";
    version = "ec63f38ba2bbc3b2c9ec82abffef3c798201458e";
    src = fetchFromGitHub ({
      owner = "KusakabeSi";
      repo = "EtherGuard-VPN";
      rev = "ec63f38ba2bbc3b2c9ec82abffef3c798201458e";
      fetchSubmodules = false;
      sha256 = "sha256-j2j4g96ooSbes5aj71HUawcblA/CtJ0dUUgXn5+RKZk=";
    });
    date = "2023-02-21";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  mybird = {
    pname = "mybird";
    version = "b0b12f37388e59b4456119d3a90d4ff69622d698";
    src = fetchFromGitHub ({
      owner = "tohojo";
      repo = "bird";
      rev = "b0b12f37388e59b4456119d3a90d4ff69622d698";
      fetchSubmodules = false;
      sha256 = "sha256-9Ufu6gGDVMZHoxZdqc2khNBsrvBcS+18IIYIcsVsdsY=";
    });
    date = "2023-02-14";
  };
  q-dns = {
    pname = "q-dns";
    version = "v0.9.0";
    src = fetchFromGitHub ({
      owner = "natesales";
      repo = "q";
      rev = "v0.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-WPVHMAau3+0jcIrRhRL5dy6h+J13LKj5GwQMJi7hGvo=";
    });
  };
  rait = {
    pname = "rait";
    version = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
    src = fetchgit {
      url = "https://gitlab.com/NickCao/RAIT";
      rev = "278188c8bae13165aa70b6a2fbbb99101fd6f4cd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6Y0s5/HUmWrZA6QmV5wYjB1M0Ab/jHM3TSruRpMRwtA=";
    };
    vendorSha256 = "sha256-SyiXhWnsECnn3ObaUl/5coq7jk7dYd66WlNihMpoCrI=";
    date = "2022-10-07";
  };
  wesher = {
    pname = "wesher";
    version = "fe2861c529968957fb553537cca93ed0ec5ceb39";
    src = fetchFromGitHub ({
      owner = "costela";
      repo = "wesher";
      rev = "fe2861c529968957fb553537cca93ed0ec5ceb39";
      fetchSubmodules = false;
      sha256 = "sha256-CoqbFobO09euN/WHTwMSHJx8Qnr9wNltRoPiZxo86ok=";
    });
    vendorSha256 = "sha256-rbJ2zwHuFJeGkaO0s8DR+yZUHfvuk/7kFaHOWPapfyA=";
    date = "2023-01-02";
  };
}
