name: CI
on:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  Atelier:
    uses: stepbrobd/atelier/.github/workflows/discover.yaml@6cf255b6e35733e746ef42208389159912ecbde2
