name: CI
on:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  Atelier:
    uses: stepbrobd/atelier/.github/workflows/discover.yaml@3eab5b4dbc2a22947fcde95ee16949d2fa8a1f67 # 2026.921.0
