name: "Check & Cachix"
on:
  push:
    branches:
      - main
      - trying
      - staging
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://imlonghao.cachix.org https://nrdxp.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = imlonghao.cachix.org-1:KGQ7+R1BXo2NsoeAxKLPfGAiHz5ofCmZO4hih7u/2Q8= nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - uses: cachix/cachix-action@v10
      with:
        name: imlonghao
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix -Lv build ".#rait"
    - run: nix -Lv build ".#pingfinder"
    - run: nix -Lv develop -c echo OK
